import { Router } from 'express';
import { authRoutes } from './authRoutes.js';
import { checkinRoutes, checkoutRoutes } from './checkinRoutes.js';
import { dashboardRoutes } from './dashboardRoutes.js';
import { folioRoutes } from './folioRoutes.js';
import { guestRoutes } from './guestRoutes.js';
import { guestPortalRoutes } from './guestPortalRoutes.js';
import { menuRoutes } from './menuRoutes.js';
import { inventoryRoutes } from './inventoryRoutes.js';
import { notificationRoutes } from './notificationRoutes.js';
import { orderRoutes } from './orderRoutes.js';
import { propertyRoutes } from './propertyRoutes.js';
import { reservationRoutes } from './reservationRoutes.js';
import { requisitionRoutes } from './requisitionRoutes.js';
import { reportRoutes } from './reportRoutes.js';
import { roomRoutes } from './roomRoutes.js';
import { settingRoutes } from './settingRoutes.js';
import { userRoutes } from './userRoutes.js';
import { auditRoutes } from './auditRoutes.js';
import { historyRoutes } from './historyRoutes.js';

export const apiRoutes = Router();

apiRoutes.use('/auth', authRoutes);
apiRoutes.use('/dashboard', dashboardRoutes);
apiRoutes.use('/properties', propertyRoutes);
apiRoutes.use('/rooms', roomRoutes);
apiRoutes.use('/reservations', reservationRoutes);
apiRoutes.use('/guests', guestRoutes);
apiRoutes.use('/checkin', checkinRoutes);
apiRoutes.use('/checkout', checkoutRoutes);
apiRoutes.use('/folios', folioRoutes);
apiRoutes.use('/menu', menuRoutes);
apiRoutes.use('/orders', orderRoutes);
apiRoutes.use('/portal', guestPortalRoutes);
apiRoutes.use('/inventory', inventoryRoutes);
apiRoutes.use('/requisitions', requisitionRoutes);
apiRoutes.use('/notifications', notificationRoutes);
apiRoutes.use('/reports', reportRoutes);
apiRoutes.use('/settings', settingRoutes);
apiRoutes.use('/users', userRoutes);
apiRoutes.use('/audit', auditRoutes);
apiRoutes.use('/history', historyRoutes);
